/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto3procesos.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu02@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagesJLabel = new javax.swing.JLabel();
        listaMensagesJScrollPane = new javax.swing.JScrollPane();
        listaMensagesJList = new javax.swing.JList<>();
        listaContactosJScrollPane = new javax.swing.JScrollPane();
        contactosJList = new javax.swing.JList<>();
        mensageJTextField = new javax.swing.JTextField();
        enviarJButton = new javax.swing.JButton();
        añadirJButton = new javax.swing.JButton();
        eliminarJButton = new javax.swing.JButton();
        contactosJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensagesJLabel.setText("Mensages");

        listaMensagesJScrollPane.setViewportView(listaMensagesJList);

        listaContactosJScrollPane.setViewportView(contactosJList);

        mensageJTextField.setText("");

        enviarJButton.setText("Enviar");

        añadirJButton.setText("Añadir");

        eliminarJButton.setText("Eliminar");

        contactosJLabel.setText("Contactos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mensageJTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarJButton))
                            .addComponent(listaMensagesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(listaContactosJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(añadirJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarJButton)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(mensagesJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactosJLabel)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensagesJLabel)
                    .addComponent(contactosJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaMensagesJScrollPane)
                    .addComponent(listaContactosJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarJButton)
                    .addComponent(añadirJButton)
                    .addComponent(eliminarJButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void addMensages(String[] listData){
        listaMensagesJList.setListData(listData);
    }
    public void addUsuarios(String[] listData){
        contactosJList.setListData(listData);
    }
    public void addEnviarActionListener(ActionListener al){
        enviarJButton.addActionListener(al);
    }
    public void addAnhadirActionListener(ActionListener al){
        añadirJButton.addActionListener(al);
    }
    public void addEliminarActionListener(ActionListener al){
        eliminarJButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirJButton;
    private javax.swing.JLabel contactosJLabel;
    private javax.swing.JList<String> contactosJList;
    private javax.swing.JButton eliminarJButton;
    private javax.swing.JButton enviarJButton;
    private javax.swing.JScrollPane listaContactosJScrollPane;
    private javax.swing.JList<String> listaMensagesJList;
    private javax.swing.JScrollPane listaMensagesJScrollPane;
    private javax.swing.JTextField mensageJTextField;
    private javax.swing.JLabel mensagesJLabel;
    // End of variables declaration//GEN-END:variables
}
